AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 60

Metrics/AbcSize:
  Max: 80

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 600

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Security/Open:
  Enabled: false
